version: "3"


networks: 
    laravel:


services:
    db:
        build:
            context: ./requirements/mariadb
            dockerfile: Dockerfile
        container_name: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 
            MYSQL_DATABASE: wordpress
            MYSQL_USER: daekim@localhost
            MYSQL_PASSWORD: 123456
        networks:
            - laravel
    wordpress:
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        container_name: wordpress
        depends_on:
            - db
        environment:
            WORDPRESS_DB_HOST: localhost:8080
            WORDPRESS_DB_USER: daekim
            WORDPRESS_DB_PASSWORD: 123456
            WORDPRESS_DB_NAME: wordpress
        networks:
            - laravel
    nginx:
        build: 
            context: ./requirements/nginx
            dockerfile: Dockerfile
        container_name: nginx
        ports: 
            - "8080:443"
        depends_on:
            - wordpress

        networks: 
            - laravel
